### ISSUE TITLE
Use of .createServer() example https -> http

### ISSUE THREAD

**Issue by MatthieuHPP** [http-party/node-http-proxy#1189]
Hi,

The method createServer() is used on httpProxy in the example https -> http.
I would like to understand why it is not .createProxyServer ?

Many thanks

**Comment by totomz** [comment]
Ihad the same problem, but then I found those [lines here](https://github.com/http-party/node-http-proxy/blob/master/lib/http-proxy.js#L57):
```
ProxyServer.createProxyServer = createProxyServer;
ProxyServer.createServer      = createProxyServer;
ProxyServer.createProxy       = createProxyServer;
```
