### ISSUE TITLE
Error: connect ECONNREFUSED and app starts listening

### ISSUE THREAD

**Issue by jcjp** [http-party/node-http-proxy#1268]
My app has a base URL of http://localhost:3000, I created a reverse proxy to send requests to http://localhost:3001 with the following configuration and codes:

```
// app.js
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var logger = require('morgan');
var httpProxy = require('http-proxy');

var app = express();

const apiProxy = httpProxy.createProxyServer({
  target: 'http://localhost:3001/'
});

app.use('/api', (req, res) => {
  apiProxy.web(req, res);
})

app.use(logger('dev'));
app.use(express.static(path.join(__dirname, 'public')));

app.get('*', (req, res) => {
  res.sendFile(path.resolve(__dirname, 'public', 'index.html'));
});

app.use(function (req, res, next) {
  next(createError(404));
});

app.use(function (err, req, res, next) {
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
```

```
//apiServer.js
var createError = require('http-errors');
var express = require('express');
var cookieParser = require('cookie-parser');

const session = require('express-session');
const MongoStore = require('connect-mongo')(session);

var app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

app.get('/books', (req, res) => {
  Books.find((err, books) => {
    if (err) {
      throw err;
    }
    res.json(books);
  })
})

app.listen(3001, (err) => {
  if (err) {
    return console.log(err);
  }
  console.log('API Server is listening on http://localhost:3001');
})
```

When I try to open my base URL, my web page opens up but when it tries to request on '/books' it does not load and returns an error log, as soon as I try to refresh my app it shows an error on my terminal:

> ...\node_modules\http-proxy\lib\http-proxy\index.js:120
>     throw err;
>     ^
> 
> Error: connect ECONNREFUSED 127.0.0.1:3001
>     at Object._errnoException (util.js:1024:11)
>     at _exceptionWithHostPort (util.js:1046:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1185:14)
> API Server is listening on http://localhost:3001

After showing the error, my base URL shows an error and when I go to my proxy URL http://localhost:3001/books I could see the books on my browser.

**Comment by denisprsa** [comment]
By looking through code you defined endpoint ` target: 'http://localhost:3001/'`, but in apiServer.js you are listnening to `http://localhost:3001/books`

**Comment by jcjp** [comment]
It looks like the culprit here is my npm script and nodemon. I have resolved my issue, it turns out that running nodemon with a script of node ./bin/www & apiServer.js only run one server.

**Comment by gopi-i** [comment]
hi @jcjp, 
Could you please tell me how did you fix it?
Thanks in advance.

**Comment by jcjp** [comment]
> hi @jcjp,
> Could you please tell me how did you fix it?
> Thanks in advance.

Sorry I was not able to login for a long time, the fix IIRC was to remove `& apiServer.js` and have it run after `node ./bin/www` without using nodemon.
