### ISSUE TITLE
Authorization header is not being passed through requests

### ISSUE THREAD

**Issue by brunosaboia** [http-party/node-http-proxy#1282]
Hello,

I am having issues trying to pass an `Authorization` header through a proxy. The code for what I am trying to do is very simple, and can be accessed [here](https://gist.github.com/brunosaboia/f299fb1ee4389b4d3f1023ca1e27d9a2).

What I want to do is to pipe a full HTTP request from a server to another. In this case, I want to redirect incoming traffic on port 3000 to port 3005. 

If I inspect the headers I receive from my sample code, I can see that the `foo` header is set correctly, but `Authorization` was simply ignored, thus the request is failing.

How to pass the HTTP `Authorization` header through?

Thanks.

**Comment by brunosaboia** [comment]
Did not receive enough attention.

**Comment by sam961** [comment]
Hello,
@brunosaboia  did you find the solution ? Are you trying to inspect  from which user the traffic is coming from ?

**Comment by brunosaboia** [comment]
@sam961 I did not. But the auth header is set on the `createProxyServer` method, under the `options.auth` object.

See https://github.com/http-party/node-http-proxy/blob/master/lib/http-proxy.js
