### ISSUE TITLE
`proxyReq.setHeader` in 'proxyReq' event callback throw 'Cannot set headers after they are sent to the client'

### ISSUE THREAD

**Issue by anson0370** [http-party/node-http-proxy#1328]
I did some debug and figured out what's happened.
In my case, this is because I was using curl to post a request with a body size bigger than 1024. curl sends a http request with header `expect: 100-continue` before sends the post request.

Looks like the problem is in Node http module:
```js
    // _http_client.js: 221
    if (this.getHeader('expect')) {
      if (this._header) {
        throw new ERR_HTTP_HEADERS_SENT('render');
      }
      // here set headers for the request, so when we call proxyReq.setHeader later, it throw an exception
      this._storeHeader(this.method + ' ' + this.path + ' HTTP/1.1\r\n',
                        this[outHeadersKey]);
    }
```

Maybe we can check is here a `expect` header before fire `proxyReq` event, or ignore the setHeader invoke?

**Comment by skleeschulte** [comment]
I found a workaround that might also help in your case: https://github.com/http-party/node-http-proxy/issues/1219#issuecomment-511110375

**Comment by jsmylnycky** [comment]
Fixed as part of https://github.com/http-party/node-http-proxy/pull/1447
