### ISSUE TITLE
how to use http-proxy in command line

### ISSUE THREAD

**Issue by IEfucker** [http-party/node-http-proxy#1340]
Installing in global env seems to fail
![http-proxy](https://user-images.githubusercontent.com/3446876/57744346-6aab7080-76fb-11e9-8d7b-2b102acffe43.png)

And didnot find any doc refering to cli

**Comment by jsmylnycky** [comment]
This project does not have a CLI mode.  You are responsible for creating the web server implementation around this module, in order to facilitate receiving a request and then handing it off to the proxy.  By that nature, a CLI implementation wouldn't work.
