### ISSUE TITLE
create proxy with http-node-proxy

### ISSUE THREAD

**Issue by opensas** [http-party/node-http-proxy#1344]
I'm trying to develop a node local proxy to `http://proxy_target.com.ar`, so far now this is what I tried

```js
const http = require('http')
const httpProxy = require('http-proxy')

var proxyOptions = {
  target: 'http://proxy_target.com.ar',
}

var proxy = httpProxy.createProxyServer({})

var server = http.createServer(function (req, res) {
  proxy.web(req, res, proxyOptions);
});

console.log("listening on port 5050")
server.listen(5050);
```

Now if I issue a curl to the proxy_target site I get:

```shell
λ curl -v -i -X GET http://proxy_target.com.ar/EEServices/consulta?wsdl

> GET /EEServices/consulta?wsdl HTTP/1.1
> Host: proxy_target.com.ar
> User-Agent: curl/7.46.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 06 Jun 2019 00:14:17 -0300
< Server: Mule Core/3.4.0
< Content-Type: text/xml
```

but If I try to do the same to my proxy:

```shell
λ curl -v -i -X GET localhost:5050/EEServices/consulta.wsdl
*   Trying ::1...
* Connected to localhost (::1) port 5050 (#0)
> GET /EEServices/consulta.wsdl HTTP/1.1
> Host: localhost:5050
> User-Agent: curl/7.46.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
server: Apache-Coyote/1.1
content-type: text/html;charset=utf-8
content-language: en
content-length: 999
date: Thu, 06 Jun 2019 03:11:15 GMT
connection: close

<html><head>
<title>Apache Tomcat/7.0.69 - Error report</title>
</head>
<body>
<h1>HTTP Status 404 - /EEServices/consulta.wsdl</h1>
<u>/EEServices/consulta.wsdl</u>
<u>The requested resource is not available.</u>
<h3>Apache Tomcat/7.0.69</h3>
</body></html>*
Closing connection 0
```

Am I missing anything?

Same question on [SO](https://stackoverflow.com/q/56470709/47633)

**Comment by jsmylnycky** [comment]
Hi @opensas 

I know its been a couple months, but going to take a stab at helping you out.  Please respond when you can whether this resolves your issue, or if you no longer are pursing an answer so we can close the issue appropriately :)

My hunch is that your Apache server is expecting a specific Host header to be passed in.  It is likely not recognizing the Host header of `localhost:5050`.  In the options of your node-http-proxy instantiation, try setting `changeOrigin: true`.  This will make it so the Host header being sent to Apache is `proxy_target.com.ar`.

**Comment by opensas** [comment]
I went ahead and ended with something inspired on this SO answer: https://stackoverflow.com/a/20354642/47633, which seems to work ok

thanks a lot for your reply
