### ISSUE TITLE
Please rename this repo from node-http-proxy to http-proxy

### ISSUE THREAD

**Issue by sylque** [http-party/node-http-proxy#1345]
It's the third time I install by mistake the npm package called [node-http-proxy](https://www.npmjs.com/package/node-http-proxy), which is a different package. Would it be possible to have the same name for both the npm package and the repo? It is very confusing.

**Comment by shirshak55** [comment]
yea github name should be changed. Its so weird to have different name. And seems like repo is not maintained so probably we should fork it with promise support and typescript. This seems so outdated.

**Comment by MartinMuzatko** [comment]
There are even packages that reverse this behavior :P
https://www.npmjs.com/package/node-docker-api -> https://github.com/AgustinCB/docker-api

**Comment by shirshak55** [comment]
@MartinMuzatko  yea I think now it is not necessary to change :) May be we can alias in npm. In github writing node will help to identify it is node based project 👍

**Comment by Falieson** [comment]
@shirshak55 99% of the time I'd agree with you  "node- " helps identify the project, but the organization is "nodejitsu" :-/
Real shame this package is unmaintained

**Comment by jsmylnycky** [comment]
Hello!

Since there is no "standard" in naming conventions, I'll be closing this ticket with no action taken.  We also are no longer maintained by nodejitsu as an org, so there is less implication as to the tech stack.

Please note that we're adding more active maintainers and will be looking to inject new life into this project over the coming months and into the future :)

If you're interested in helping out, please see the current pinned issue #1354

**Comment by sylque** [comment]
@jsmylnycky , I'm not sure you got the point here, so please let me rephrase:
- This Github repository - which I think is the main entry point for developers - is called `http-party/node-http-proxy`.
- I believe most developers returning to this package will do the same mistake I've done twice: they won't read the documentation (because they think they now) and will type `npm install node-http-proxy --save` (notice the wrong npm package name, the correct one being [http-proxy](https://www.npmjs.com/package/http-proxy)).
- Unfortunately, the above mistake won't trigger any error, because there *is* a npm package called   [node-http-proxy](https://www.npmjs.com/package/node-http-proxy)! The time they realize they've installed the wrong package and cleanup the mess, they'll have lost 15 minutes.

So what is needed here is to have the same name for the Github repo and the npm package.

**Comment by hcldan** [comment]
> I believe most developers returning to this package will do the same mistake I've done twice: they won't read the documentation (because they think they now) and will type npm install node-http-proxy --save (notice the wrong npm package name, the correct one being http-proxy).

I'm so glad this ticket exists (as I was searching for if this project was maintained).  I did the exact same thing, and thought it was odd there were so many security vulnerabilities listed.
