### ISSUE TITLE
question on https

### ISSUE THREAD

**Issue by moeinrahimi** [http-party/node-http-proxy#1374]
I'm making a simple proxy server for my house network, it simply blocks some websites, can i proxy https without ssl certificate ? or is there any free ssl, and also I'm simply running my proxy server only on localhost

**Comment by jsmylnycky** [comment]
This question doesn't necessarily impact the project here, as you wouldn't use node-http-proxy for SSL termination of incoming requests. I'd recommend running nginx infront of your node app and terminate SSL there.

You can do self-signed certs for localhost, or if you want to get an actual domain name, check out https://letsencrypt.org/ and some documentation you can find pretty easily on setting up auto cert generation to handle expiration times.
