### ISSUE TITLE
Why proxyReq.path is repeated?

### ISSUE THREAD

**Issue by mqliutie** [http-party/node-http-proxy#1399]
![image](https://user-images.githubusercontent.com/11795518/69231656-6ab58d00-0bc4-11ea-9f65-c7456a49afe5.png)

The `req.url` is `localhost:9000/admin/order/orderManager/orderList.do`

The target value is `http://10.100.9.148:8080/admin/order/orderManager/orderList.do` that is assembled. 

But in `proxyReq` event the value of `proxyReq.path` is `/admin/order/orderManager/orderList.do/admin/order/orderManager/orderList.do`

Expected value should be  `/admin/order/orderManager/orderList.do`

I think I should set the root path to `'/'` but I don't know how to do .

Any  problems will be appear if I change the req.url ?
```
req.url = '/';
```

**Comment by jsmylnycky** [comment]
The target url automatically takes the incoming path and appends it to the configured target.  If you're intending for the target to always be what you have it set to, or want to control differently how the proxy target url is built, you might want to look at disabling the prependPath option.

**Comment by mqliutie** [comment]
@jsmylnycky thanks
