### ISSUE TITLE
Replace single chunks of an websocket stream

### ISSUE THREAD

**Issue by karlTGA** [http-party/node-http-proxy#1414]
Hello, 
at first thank you for the project. I works like expected and I think my problem is a corner case. I want to modify messages of an websocket stream to add credentials at the backend. I think I solved the most problems but now I find no way to replace the chunk I want to change. But maybe a code snippet says more.

``` javascript
  server.on("upgrade", function(req, socket: Socket, head) {

    socket.on("data", chunk => {
      // receive the original chunk here
      const updatedChunk = processChunk(chunk)

      // what to do now to send the updatedChunk not the original?
    });

    proxy.ws(req, socket, head);
  });
```

Maybe somebody has an idea.

**Comment by red-0ne** [comment]
Have you tried `socket.write` ?

**Comment by karlTGA** [comment]
I think I tried that and it did not work. Anyway, in the end I used a local websocket server and a websocket client in the backend and a simple bridge between. The solution is not nice but it works.
