### ISSUE TITLE
Proxy rotation http > https proxies

### ISSUE THREAD

**Issue by jhgeluk** [http-party/node-http-proxy#1426]
Hi,

Is there any example to create a proxy rotation server? I wan't to create a http proxy that will forward the request to a https proxy that will eventually execute the request.

I've tried to create an example, but I can't seem to get it working. The page keeps loading and never resolves.

I'm using the `https-proxy-agent` library to create agents for using a proxy.

`this.proxy = Server.createProxyServer({ toProxy: true });
        
        this.proxyServer = http.createServer((req, res) => {
            let proxyOptions = url.parse('https://11.1.101.xxx:1111/');
            let fullUrl = url.parse(req.url);

            proxyOptions['headers'] = { 'Proxy-Authentication': 'Basic ' + Buffer.from('username:password').toString('base64') };

            const tempAgent = new ProxyAgent(proxyOptions);

            this.proxy.web(req, res, {
                agent: tempAgent,
                secure: false,
                changeOrigin: true,
                target: req.url
            });
            
        });

        this.proxyServer.listen(8088);`

Is there a working example somewhere? What am I doing wrong.

**Comment by leinadzaid21** [comment]
this.proxyServer = http.createServer((req, res) => {
        let proxyOptions = url.parse('https://11.1.101.xxx:1111/');
        let fullUrl = url.parse(req.url);

        proxyOptions['headers'] = { 'Proxy-Authentication': 'Basic ' + Buffer.from('username:password').toString('base64') };

        const tempAgent = new ProxyAgent(proxyOptions);

        this.proxy.web(req, res, {
            agent: tempAgent,
            secure: false,
            changeOrigin: true,
            target: req.url
        });
        
    });

    this.proxyServer.listen(8088);`
