### ISSUE TITLE
Modify response Websocket. 

### ISSUE THREAD

**Issue by alshaboti** [http-party/node-http-proxy#1434]
Is there a way to modify/block the WebSocket response similar to modify the HTTP response as in there [here](https://github.com/http-party/node-http-proxy#modify-response)?

I mean how can I modify the Websocket response in here.
```
//
// Listen for the `open` event on `proxy`.
//
proxy.on('open', function (proxySocket) {
  // listen for messages coming FROM the target here
  proxySocket.on('data', hybiParseAndLogMessage);
});

```
thanks

**Comment by kqdjacky** [comment]
Hi @alshaboti  , did you find the solution?

**Comment by alshaboti** [comment]
I don't remember sorry!
