### ISSUE TITLE
README examples has wrong listening port numbers

### ISSUE THREAD

**Issue by Subomi** [http-party/node-http-proxy#969]
In section Setup a stand-alone proxy server with custom server logic: 
We have: 
`var server = http.createServer(function(req, res) {
  // You can define here your custom logic to handle the request
  // and then proxy the request.
  proxy.web(req, res, { target: 'http://127.0.0.1:5060' });
});

console.log("listening on port 5050")
server.listen(5050);`

Instead of: 
`var server = http.createServer(function(req, res) {
  // You can define here your custom logic to handle the request
  // and then proxy the request.
  proxy.web(req, res, { target: 'http://127.0.0.1:5050' });
});

console.log("listening on port 5050")
server.listen(5050)'

And also the same thing in section Setup a stand-alone proxy server with proxy request header re-writing

**Comment by indexzero** [comment]
Fixed in https://github.com/http-party/node-http-proxy/pull/970
